version: "3.1"
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT}/grafana:/var/lib/grafana
    networks:
      - aspnetcoreapp-network

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ${ROOT}/influxdb:/var/lib/influxdb
    networks:
      - aspnetcoreapp-network

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    volumes:
      - ${ROOT}/chronograf:/var/lib/chronograf
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge