
### dotnet
POST http://localhost:8086/query?q=CREATE DATABASE dotnet

### chronograf
POST http://localhost:8086/query?q=CREATE DATABASE chronograf

###  telegraf
POST http://localhost:8086/query?q=CREATE DATABASE telegraf

###

GET http://localhost:5000/api/hello/a1

###

GET http://localhost:5000/api/hello/a1